const express = require("express")
const cors = require("cors")
const app = express()
const cookie_parser = require("cookie-parser")
const port = process.env.PORT | 5000

//middleware
app.use(express.json())
app.use(cors({
    origin : ["https://web.caponmada.com","https://caponmada.com","http://localhost:3000"],
    methods : ["GET","POST","PUT","DELETE"]
}))
app.use(cookie_parser())
//import for task road
const multer = require("./multer_middleware")
const parent = require("./circuit_manager_only_by_admin/get_all_parent_road_by_public_or_by_admin")
const parentId = require("./circuit_manager_only_by_admin/get_parent_way_to_update_by_admin")
const insertParent = require("./circuit_manager_only_by_admin/add_circuit_by_users")
const updateParent = require("./circuit_manager_only_by_admin/update_parent_circuit_by_id")
const deleteParent = require("./circuit_manager_only_by_admin/delete_parent_circuit_by_users")
const child = require("./circuit_manager_only_by_admin/get_all_under_road_by_parent_id")
const childId = require("./circuit_manager_only_by_admin/get_one_road_by_public_or_by_admin")
const insertChild = require("./circuit_manager_only_by_admin/add_under_circuit_by_users")
const updateChild = require("./circuit_manager_only_by_admin/update_child_way_by_admin")
const deleteChild = require("./circuit_manager_only_by_admin/delete_under_circuit_by_users")
const loginUser = require("./Login_and_subscription_and_log_out/login")
const Users = require("./Login_and_subscription_and_log_out/getAllAdmin")
const UpdateUser = require("./Login_and_subscription_and_log_out/updatePass")
const newAdmin = require("./Login_and_subscription_and_log_out/newAdmin")
const loginMember = require("./Login_and_subscription_and_log_out/member_auth/member_login")
const updateMember = require("./Login_and_subscription_and_log_out/member_auth/updatePass")
const signup = require("./Login_and_subscription_and_log_out/member_auth/subscription")
const Members = require("./Login_and_subscription_and_log_out/member_auth/get_all_member")
const contacts = require("./get_contact")
const contact = require("./add_contact")
const contact1 = require("./getOneContact")
const commentaries = require("./commentary_by_member/get_all_commentary_to_show_in_page")
const commentary = require("./commentary_by_member/add_commentary_by_member")
const addCommentary = require("./commentary_by_member/add_commentary_by_member")
const AddLike = require("./likeByMember.js/AddLikeByMember")
const deleteMember = require("./Login_and_subscription_and_log_out/member_auth/deleteMember")
const adminMiddleware = require("./middleware/jsonverify")
const Image = require("./circuit_manager_only_by_admin/get_image")
// app.use("/admin/",adminMiddleware)
app.get("/parent",parent)
app.get("/:id/parent",parentId)
app.post("/admin/insert/parent",multer,insertParent)
app.put("/admin/update/parent",multer,updateParent)
app.delete("/admin/delete/:id/parent",deleteParent)
//child
app.get("/:parent/childs",child)
app.get("/:id/child",childId)
app.post("/admin/insert/child",multer,insertChild)
app.put("/admin/update/child",multer,updateChild)
app.delete("/admin/delete/:id/child",deleteChild)
//User
app.post("/login",multer,loginUser)
app.get("/users",Users)
app.put("/password",multer,UpdateUser)
app.post("/admin/new",multer,newAdmin)
//Member 
app.post("/login/member",multer,loginMember)
app.put("/password/member",multer,updateMember)
app.post("/signup",multer,signup)
app.get("/admin/all",Members)
app.delete("/admin/member/:id/delete",deleteMember)
//Contact
app.post("/contact",multer,contact)
app.get("/admin/contacts",contacts)
app.get("/admin/:id/contact",contact1)
//commentary
app.get("/admin/commentaries",commentaries)
app.get("/admin/:id/commentary",commentary)
app.post("/commentary",multer,addCommentary)
//Like
app.post("/like",AddLike)
//get image
app.get("/get/:name",Image)
app.listen(port,() => console.log("http://localhost:5000"))
